name = "CodeInfoTools"
uuid = "bc773b8a-8374-437a-b9f2-0e9785855863"
authors = ["McCoy Becker <mccoybecker@gmail.com>"]
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
