name = "CodeInfoTools"
uuid = "bc773b8a-8374-437a-b9f2-0e9785855863"
authors = ["McCoy R. Becker <mccoyb@mit.edu>, Xiu-Zhe (Roger) Luo <rogerluo.rl18@gmail.com> and Valentin Churavy <vchuravy@mit.edu>"]
version = "0.2.4"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
